New design
FreiFahren/frontend pull request #128
Opened 2024-04-20 15:12 UTC by johan-t

minor changes to ui

2024-04-20 15:22 UTC, johan-t commented
I will fix the tests later

2024-04-20 15:23 UTC, brandesdavid commented
![Screenshot 2024-04-20 at 17 21 06](https://github.com/FreiFahren/frontend/assets/61701882/e3b18959-4798-4b76-831d-173457c6f5f7)
why is the button stretched out xD
![Screenshot 2024-04-20 at 17 21 41](https://github.com/FreiFahren/frontend/assets/61701882/10353c5c-ea22-43fb-b8d4-97b6b93f07aa)
does the down button have a lighter color?
![Screenshot 2024-04-20 at 17 23 18](https://github.com/FreiFahren/frontend/assets/61701882/95df2773-c401-4582-aa22-d19e78b44e49)
could you move the down button a bit more to the right please?

what about text padding?

2024-04-20 15:23 UTC, brandesdavid commented
great changes though!!!

2024-04-20 15:26 UTC, brandesdavid commented on src/components/Buttons/ReportButton/ReportButton.css
>      height: 90px;
maybe use min-height and min-width?

2024-04-20 15:32 UTC, brandesdavid requested changes
a question: was the figma only for orientation or did you wanted to use an exact replication of the styles?

2024-04-20 16:06 UTC, johan-t commented
> a question: was the figma only for orientation or did you wanted to use an exact replication of the styles?

I used it just as a reference as some of it was not applicable or consistent

2024-04-20 16:15 UTC, johan-t commented
> ![Screenshot 2024-04-20 at 17 21 06](https://github.com/FreiFahren/frontend/assets/61701882/e3b18959-4798-4b76-831d-173457c6f5f7)
> 
> why is the button stretched out xD
> 
I think it looks stretched because it is much bigger than the utility  button, but it is not streched irl
> ![Screenshot 2024-04-20 at 17 21 41](https://github.com/FreiFahren/frontend/assets/61701882/10353c5c-ea22-43fb-b8d4-97b6b93f07aa)
> 
> does the down button have a lighter color?
> 
Yes I asked you if I could use the same color as the location marker to be consistent 
> ![Screenshot 2024-04-20 at 17 23 18](https://github.com/FreiFahren/frontend/assets/61701882/95df2773-c401-4582-aa22-d19e78b44e49)
> 
> could you move the down button a bit more to the right please?

Yes will do 
> 
> 
> 
> what about text padding?

Standard text padding is sub optimal as this it is very different for each situation meaning we would have to overwrite it every time

2024-04-21 09:14 UTC, brandesdavid commented
@johan-t 

The button is stretched. (100x90)
![Screenshot 2024-04-21 at 11 02 25](https://github.com/FreiFahren/frontend/assets/61701882/c25187ac-a765-4501-a405-eca6d70b4a54)

when changing top to -30px and -33px, the down button  ```button.close-button``` border gets lighter. that is what i mean. 
![Screenshot 2024-04-21 at 11 09 49](https://github.com/FreiFahren/frontend/assets/61701882/b922fcba-8733-4ea1-a25d-0d649da185de)

![Screenshot 2024-04-21 at 11 09 53](https://github.com/FreiFahren/frontend/assets/61701882/9e0f77bc-e38f-4a73-8662-26380e3a9c82)

2024-04-21 09:47 UTC, johan-t commented
> @johan-t
> 
> The button is stretched. (100x90) ![Screenshot 2024-04-21 at 11 02 25](https://private-user-images.githubusercontent.com/61701882/324235596-c25187ac-a765-4501-a405-eca6d70b4a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTMwNzAsIm5iZiI6MTcxMzY5Mjc3MCwicGF0aCI6Ii82MTcwMTg4Mi8zMjQyMzU1OTYtYzI1MTg3YWMtYTc2NS00NTAxLWE0MDUtZWNhNmQ3MGI0YTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5NDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzcxM2E2ZTE4NzQxN2M0NGE0YTZkYTE3YWExYWY2NzY5ZDRmYzE5OTA4NmJiMmJkOGEwNmRmYzA3ZmQ3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.--X55sADVk75pBwwkzmtHstjBljlnBoFtsrePxrRyM4)
> 
> when changing top to -30px and -33px, the down button `button.close-button` border gets lighter. that is what i mean. ![Screenshot 2024-04-21 at 11 09 49](https://private-user-images.githubusercontent.com/61701882/324235968-b922fcba-8733-4ea1-a25d-0d649da185de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTMwNzAsIm5iZiI6MTcxMzY5Mjc3MCwicGF0aCI6Ii82MTcwMTg4Mi8zMjQyMzU5NjgtYjkyMmZjYmEtODczMy00ZWExLWEyNWQtMGQ2NDlkYTE4NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5NDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmRmMmUwYjA1YWY3ZjM2NTMzMGMwMjE0OWJmMjI1N2M4MDUzZGM2M2EyZDkwNWIxN2MzOGU1ZDY2ZDMwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AO61t7oflmwBOBc5RMPIAXG3GJY3n5CpGvonFLPwNL4)
> 
> ![Screenshot 2024-04-21 at 11 09 53](https://private-user-images.githubusercontent.com/61701882/324235965-9e0f77bc-e38f-4a73-8662-26380e3a9c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTMwNzAsIm5iZiI6MTcxMzY5Mjc3MCwicGF0aCI6Ii82MTcwMTg4Mi8zMjQyMzU5NjUtOWUwZjc3YmMtZTM4Zi00YTczLTg2NjItMjYzODBlM2E5YzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5NDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjJjMDI5YmQ4ZTYxMDk1MDU1ZmMyNTFjZTI4YTU4ZWNlZGNiNjBhNDYyOTc4ZmFhNTE2NDRjNjZlMzM0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JB3PM5Culs59X05sY5YfFcQxQQMujusINA9cPAVB19E)

you are right , oopsie

2024-04-21 10:05 UTC, brandesdavid commented
changed some styles, could you maybe please add some documentation for styling? (like classes or variables etc)
but you can review now and merge if you want to @johan-t

2024-04-21 10:12 UTC, johan-t commented
> changed some styles, could you maybe please add some documentation for styling? (like classes or variables etc) but you can review now and merge if you want to @johan-t

What kind of documentation were you thinking? I am not sure if we need docs for the variables as they are written in plain english same for the classes and it would be super long to have documentation for each class. Or are there specific classes that need documentation_

2024-04-21 12:50 UTC, merged