Display lines on map
FreiFahren/frontend pull request #132
Opened 2024-04-25 18:30 UTC by johan-t

## Describe the issue:
Users had a hard time navigating the map because you had to know the berlin public transport system to use the app.

## Explain how you solved the issue:
I got the coordinates of the lines from overpass turbo, saved them in lineData.js and added them as a line with map libre. I also showed the stations using the coordinates from StationsList.json.
When you start to zoom into one line you will see the label of the line.

## Additional notes or considerations:
I added StationsList.json to the frontend as it would be too slow to get the station data from the backend for each rendering of the map imo, but I could change it for consistency but we would have a much slower initial page load.

Also some of the stations coordinates are wrong or incomplete not sure if I should fix it in this pr or just take care of it at a later time.

2024-04-25 22:15 UTC, brandesdavid commented on src/components/Map/Map.tsx
> +import stationsData from '../../data/StationsList.json';
Nonono big big data inconsistency problem. You told me some months ago we shouldn't do that? Why now? Data still stays inconsistent. If you really want to include lineData, then at least also include it in ReportForm data, because we're always fetching them already

2024-04-25 22:16 UTC, brandesdavid commented on src/components/Map/Map.tsx
> +import lineData from '../../data/lineData.js';
better naming please

2024-04-25 22:16 UTC, brandesdavid commented on src/components/Map/Map.tsx
> +                                    'text-field': feature.properties.ref,
refactor this into a const

2024-04-25 22:16 UTC, brandesdavid commented on src/components/Map/Map.tsx
> +                                    'text-color': '#000',
this too

2024-04-25 22:19 UTC, brandesdavid commented on src/components/Map/Map.tsx
> +                    <Source id='lineSource' type='geojson' data={lineData}>
maybe refactor this layer into a new folder. always separate base map with layers and sources

2024-04-25 22:21 UTC, brandesdavid commented on src/utils/mapUtils.tsx
> +export function convertStationsToGeoJSON(stationsData: { [key: string]: StationProperty }) {
great function resusability. but perhaps we should predefine the file with all geojson etc into the backend and fetch it from there, as we want to use the least possible amount of computation on frontend

2024-04-25 22:22 UTC, brandesdavid commented
please also note the stations down that have wrong or incorrect positions. some stations i have marked between the s bahn und u bahn etc.

2024-04-25 22:23 UTC, brandesdavid requested changes
looks good the styling. maybe we should rethink the json approach a bit, but gj

2024-04-26 16:12 UTC, johan-t commented
I changed the things that were requested opend two issues:
- issue regarding switching reporForm and ask for location to local json
- issue to add all of the types to the types.tsx file

2024-04-26 20:26 UTC, brandesdavid approved these changes

2024-04-27 12:52 UTC, merged