darkmode + remove all of the labels from the jawg map
FreiFahren/frontend pull request #137
Opened 2024-05-01 19:18 UTC by brandesdavid

## Describe the issue:

we need darkmode map, the sea colors should be changed, and because of the jawg map integrations, we have to include or own stations and names

## Explain how you solved the issue:
- added icons and station names
- added darkmode map
- added zoom levels for icons and names
- changed up the props to have line based icons

## Additional notes or considerations:
this is the first iteration of the darkmode. later, we can try to recreate the lines inside the vector lines/routes of the map, with station labels and more intuitive station name opacity levels

2024-05-02 08:31 UTC, brandesdavid commented
> @brandesdavid Is this a branch from the darkmode branch? Or is this informally depending on darkmode?

no not really, i added the jawg dark mode map only

2024-05-02 08:41 UTC, johan-t commented
> > @brandesdavid Is this a branch from the darkmode branch? Or is this informally depending on darkmode?
> 
> no not really, i added the jawg dark mode map only

@brandesdavid But why did you add the darkmode map in this pr? I am a bit confused

2024-05-03 06:50 UTC, johan-t requested changes
Some smaller changes are needed. The map looks good

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +        image.src = ubahn_icon; // replace with the path to your icon
remove comment

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +        const image = new Image(16,16);
I could set the icon to be a bit smaller maybe 12 x 12 but be weary of image looking like shit due to compression

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +    useEffect(() => {
Maybe avoid code duplication by using a [factory](https://en.wikipedia.org/wiki/Factory_method_pattern)

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +    const priorityStations = ['Hauptbahnhof', 'Gesundbrunnen', 'Jungfernheide', 'Ostkreuz', 'Südkreuz', 'Westkreuz'];
Do you know what is up with this as it is not always visible on the same zoom level?

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +                    //     'step',
Please remove the comment

2024-05-03 06:50 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +                            ['in', 'S2', ['get', 'lines']],
I think some of the lines are missing such as S45, S46, S47 and maybe something more

2024-05-04 15:18 UTC, johan-t approved these changes

2024-05-04 15:18 UTC, johan-t commented on src/components/Map/MapLayers/StationLayer/StationLayer.tsx
> +class IconFactory {
Beautiful

2024-05-05 12:57 UTC, brandesdavid commented
nice

2024-05-05 12:57 UTC, merged