marker information
FreiFahren/frontend pull request #14
Opened 2024-03-13 20:41 UTC by brandesdavid

clicking on the marker shows the station, and if existing, the direction and line

2024-03-13 21:31 UTC, johan-t requested changes
I am getting this error when running and reporting a staion.

Markers.tsx:27 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Markers.tsx:27:1
    at Array.map (<anonymous>)
    at Markers (Markers.tsx:25:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)

2024-03-13 21:37 UTC, johan-t requested changes

2024-03-13 21:37 UTC, johan-t commented on src/functions/dbUtils.tsx
> +export function IdToStation(id: string): string {
I think it would be better if we would define this as an endpoint in the backend. This is due to the separation of concerns best practice: https://en.wikipedia.org/wiki/Separation_of_concerns

Also I am sure that we could use this function in other places such as the bot so having this function in the backend makes it better.

2024-03-13 21:46 UTC, johan-t commented on src/functions/dbUtils.tsx
> +export function IdToStation(id: string): string {
Also if we have to push the name of the station in the GET request that is not an issue because it only makes the size of the request bigger by a couple of bytes.

2024-03-15 10:32 UTC, brandesdavid commented
> Markers.tsx:27 Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> at Markers.tsx:27:1
> at Array.map ()
> at Markers (Markers.tsx:25:1)
> at renderWithHooks (react-dom.development.js:16305:1)
> at updateFunctionComponent (react-dom.development.js:19588:1)
> at beginWork (react-dom.development.js:21601:1)
> at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
> at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
> at invokeGuardedCallback (react-dom.development.js:4277:1)
> at beginWork$1 (react-dom.development.js:27451:1)

This could happen when you use a localhost database and the data is not up-to-date. 
On an api call, the returned data would be ``` [] ```, thus undefined and not iterable.
Added a protection against it, in the new commit

2024-03-15 10:34 UTC, brandesdavid commented on src/functions/dbUtils.tsx
> +export function IdToStation(id: string): string {
Added backend functionality to have the query parameter ?names=true, to return the names instead of id

https://github.com/FreiFahren/backend/commit/1cca64686f94805e1752bb929e537bd89699f938

2024-03-15 11:28 UTC, johan-t commented
I will test this later

2024-03-15 13:54 UTC, johan-t requested changes
It does not show the line and direction when you are reporting it via the form so seems to be something wrong, not sure what

2024-03-15 14:01 UTC, johan-t requested changes

2024-03-15 14:01 UTC, johan-t commented on src/components/Markers/Markers.tsx
> +		const station = item.StationID || '';
Or if this is the name and not the id could you rename the prop. in the struct to stationName or so?

2024-03-15 14:18 UTC, brandesdavid commented on src/components/Markers/Markers.tsx
> +			if (process.env.NODE_ENV === 'development') {
We only log that the item.Coordinates is not an array if nothing is returned. If we're on production, this will not be logged

2024-03-15 14:19 UTC, brandesdavid commented on src/functions/dbUtils.tsx
> +// export async function IdToStation(id: string): Promise<string> {
My bad

2024-03-15 14:25 UTC, brandesdavid commented
> It does not show the line and direction when you are reporting it via the form so seems to be something wrong, not sure what

Are you using the localhost database? Is it updated already?
Works perfectly fine here

2024-03-15 17:06 UTC, closed without merging