Opacity
FreiFahren/frontend pull request #27
Opened 2024-03-17 21:17 UTC by brandesdavid

- moved the MarkerData props to a new file for better overview
- added opacitymarker.tsx, which calculates the timestamp and their differences, gradually decreasing the opacity to zero and then destroys the element
   - the fucking timestamp was bugged as fuck
   - analina did not help for the calculation

2024-03-17 21:26 UTC, johan-t commented
I'll have a look at it first thing in the morning

2024-03-18 11:39 UTC, johan-t requested changes
I think having three different and a sub component causes the code to be harder to work with than it needs to be.

Besides that it is good code that is clean and efficient. Good Job

2024-03-18 11:39 UTC, johan-t commented on src/components/Markers/Markers.tsx
> -export type MarkerData = {
Honestly I think we should keep the props and the datatype in the same file, because when working with this function for a person without any previous knowledge of the codebase it is essential to know what comes into the function and having the props in another file makes it pretty annoying because you will need to switch files all of the time when checking the props.

Also the file it not that long so we can handle the props and data type in the same file

2024-03-18 11:39 UTC, johan-t commented on src/components/Markers/Markers.tsx
>    const [data, setData] = useState<MarkerData[]>([]);
Can we find a more descriptive name than data?

2024-03-18 11:39 UTC, johan-t commented on src/components/Markers/Markers.tsx
> +              <MarkerComponent markerData={item} index={index} key={index}/>
I think this is a bit of a strange abstraction because we are calling Makers as a component and inside of Markers we are calling the MarkersComponent. I think this is a bit confusing as we are only using the MarkerComponent in this case so it makes the code a bit complexer than it needs to be. Also it is a bit confusing because the structure is breaking the format of having one component per folder where the component and file have the same name

2024-03-18 11:39 UTC, johan-t commented on src/components/Markers/OpacityMarker.tsx
> +            html: `<div style="background-color:rgba(255,0,0,${opacity});width:20px;height:20px;border-radius:50%;"></div>`,
I don't know but is it possible to avoid inline styles here by using the declared class?

2024-03-18 11:41 UTC, johan-t commented
Also I just noticed a bug, after a station has fadded you cannot report it again or it wont be displayed

2024-03-18 11:49 UTC, johan-t requested changes

2024-03-18 11:49 UTC, johan-t commented on src/components/Markers/Markers.tsx
> +              <MarkerComponent markerData={item} index={index} key={index}/>
I think using index as a key is generally discourages as this can likely lead to bugs:

https://legacy.reactjs.org/docs/lists-and-keys.html

Maybe it is better to use the station id or we could generate an id

2024-03-18 11:49 UTC, johan-t commented on src/components/Markers/Markers.tsx
>          data.map((item, index) => {
Could we use names that represent the things we are iterating over instead of item? That way it is clearer what the code does or what data it is using. Otherwise the entire code is a big blackbox

2024-03-18 11:49 UTC, johan-t commented on src/components/Markers/OpacityMarker.tsx
> +    const timestampMarker = new Date(timestamp.replace(/T|Z/g, ' ')).getTime();
Maybe the name timestamp is better then timestampMarker to avoid confusing it with the actual Marker

2024-03-18 14:46 UTC, brandesdavid commented on src/components/Markers/OpacityMarker.tsx
> +            html: `<div style="background-color:rgba(255,0,0,${opacity});width:20px;height:20px;border-radius:50%;"></div>`,
sadly that is not easy. i tried it before, but react will crash because it got a render overload, always calling the opacity function and renders too many opacity icons at the same time. if we have 20 markers, we're actually rendering 40 components - 20 markers, and 20 opacity icons. the opacity icons also have to update every second to slowly decrease

2024-03-18 14:47 UTC, brandesdavid commented on src/components/Markers/Markers.tsx
> +              <MarkerComponent markerData={item} index={index} key={index}/>
changed the file directorys. Markers are now in Map folder, as they are similar components build on leaflet. Marker folder has the markercontainer, that hold the specific markers.

2024-03-18 15:48 UTC, brandesdavid commented on src/components/Markers/OpacityMarker.tsx
> +    const timestampMarker = new Date(timestamp.replace(/T|Z/g, ' ')).getTime();
changed to timestampSeconds as timestamp is already used.

2024-03-18 20:10 UTC, johan-t approved these changes
I think you will need to explain the file structure to me but it looks good.

Great job! 💯

2024-03-18 20:53 UTC, brandesdavid commented
> I think you will need to explain the file structure to me but it looks good.
> 
> Great job! 💯

❤️

2024-03-18 20:53 UTC, merged