Darkmode
FreiFahren/frontend pull request #73
Opened 2024-03-25 13:10 UTC by brandesdavid

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Also, include relevant motivation and context. List any dependencies that are required for this change.

Fixes: #

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Checklist:

Before submitting your PR, please review the following checklist:

- [ ] I have performed a self-review of my own code or materials.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Additional Information:

Any additional information that you believe is important and relevant to the review of this PR.

2024-03-26 20:53 UTC, johan-t commented
Great work, looks fantastic design wise I have only three recommendations:

1. Make the green a bit darker while it is very good that the green spaces are more visible to make it eaiser to orientate oneself, I think due to the high brightness of the green there is too much attention on it
2. Can you change the darkmode button to only be the icon and not a regular button that way we avoid shifting too much attention to the dark mode/ light mode button and avoid shifting the attention from the give feedback button
3. Can you remove the borders for all of the buttons etc. in dark mode, it is inconsistent with the light mode and does not add anything except that it makes the ui a bit more complicated?

2024-03-26 21:43 UTC, johan-t requested changes
Some changes and new approach needed, feel free to leave this be and first go after all of the issues with a higher prio we can talk about this one again when I am back in Berlin.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +    outline: 4px solid #222121 !important;
Please use css variables and avoid !important at all costs

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +.dark-mode {
Is it possible to instead creating darkmode css variables and simply checking once dark or light mode and loading the correct instances of the variables?

Check out this article that describes the best practice when creating dark modes: https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8

When we do it this way we avoid having messy code and make it very easy to maintain and avoid bugs in the long run

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +.dark-mode {
Otherwise we have to write every css class 2 times meaning double the work, but if we just change the instance of the variable it is very easy to write new classes in the future.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +.dark-mode {
You can check out [Memoriter](https://github.com/MemoriterApp/Memoriter/blob/main/src/index.css) for an example of a pure css darkmode

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.tsx
> +    const { currentThemeLayer, setCurrentThemeLayer } = useContext(LayerContext);
Try saving the theme in localstorage you can avoid useContext complexity and also we avoid that the user has to reset the theme on every page load.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.tsx
> +			<button className={(currentThemeLayer === 'Light') ? 'toggle-layer-button' : 'toggle-layer-button dark-mode'  } onClick={toggleThemeLayer}> {currentThemeLayer === 'Light' ? <span>☀️</span> : <span
if we use a pure css darkmode we avoid messy classes like this.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +.dark-mode h1 {
Since .dark-mode and .dark-mode h1 are a global class that are used everywhere it is better to save stuff like that in index.css

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Layers/StandardLayer.tsx
> +const StandardLayer = (props: StandardLayerProps) => {
Can you use React.FC so that we are consistent with all of the other component declarations

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Layers/DarkLayer.tsx
> +const DarkLayer = (props: StandardLayerProps) => {
please use React.FC to be consistent

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Markers/Classes/OpacityMarker/OpacityMarker.tsx
> +    const { currentThemeLayer } = useContext(LayerContext);
I am getting these two warnings when running, can we avoid them?

[eslint] 
src/components/Map/Markers/Classes/OpacityMarker/OpacityMarker.tsx
  Line 55:8:  React Hook useEffect has a missing dependency: 'currentThemeLayer'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/components/Map/Markers/Classes/OpacityMarker/OpacityMarker.tsx
  Line 55:8:  React Hook useEffect has a missing dependency: 'currentThemeLayer'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

2024-03-26 21:43 UTC, johan-t commented on src/functions/uiUtils.tsx
> +export const darkModeIds = ['report-button', 'toggle-layer-button', 'util-button']
is darkModeIds the correct variable name? Because arent these classes and also arent they all the light mode classes?

2024-03-26 21:43 UTC, johan-t commented on src/functions/uiUtils.tsx
> +	for (const id of ids) {
please rename id to classname because when we are getting by className we either have a bug or they are classNames but called ids which is very confusing

2024-03-26 21:43 UTC, johan-t commented on src/functions/uiUtils.tsx
> +export const setDarkMode = (ids: string[]) => {
I think we should remove this and exchange this for a pure css darkmode because handling this will get unmaintainable very fast.

2024-03-26 21:43 UTC, johan-t commented on src/index.css
> +.leaflet-zoom-anim .leaflet-zoom-animated {
Great work there is a noticeable improvement!!!

2024-03-26 21:43 UTC, johan-t commented on src/index.css
> +  outline: 4px solid white !important;
please use vars and avoid !important at all costs

2024-03-26 21:43 UTC, johan-t commented on src/index.css
> +  outline: 4px solid white !important;
!important are hacks and are always a good sign that something is not maintainable or very good code when you have to use !important.

2024-03-26 21:43 UTC, johan-t commented on src/index.css
> +  outline: 4px solid white !important;
If we keep !important we will very soon have an !important battle where we have !important !important !important !important for each class.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/LayerButton/LayerButton.css
> +@media screen and (min-width: 999px) {
Good work on using mobile first media queries

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Map.css
> +  /* layer button */
please remove the comment

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Layers/StandardLayer.tsx
> +			} else {
This introduces a bug where when you have declined the position it will move you back to the center of berlin every 10 seconds.

2024-03-26 21:43 UTC, johan-t commented on src/functions/uiUtils.tsx
> +export const darkModeIds = ['report-button', 'toggle-layer-button', 'util-button']
An example for how unmaintainable this kind of dark mode is that there is no darkmode for the report-form. Error like this happen VERY easily with this kind of an approach.

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Map.css
> +  .leaflet-control-layers {
Can we change this back to display:none so that it is not being rendered on mobile, right now it is being rendered, making the page slower but not visible on mobile

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Map.tsx
> +    const maxBounds = latLngBounds([52.96125019866001, 12.509131386425151],
good idea!

2024-03-26 21:43 UTC, johan-t commented on src/components/Map/Markers/Classes/LocationMarker/LocationMarker.tsx
> +     initialPosition: LatLngTuple | null;
👍 cleaner code == better code

2024-03-26 21:43 UTC, johan-t commented on src/components/UtilModal/UtilModal.css
> +    padding: 0%;
make 0 or remove instead of 0% is just a bit cleaner

2024-03-26 21:43 UTC, johan-t commented on src/components/UtilModal/UtilModal.css
>  .util-modal ul li a {
can you add the underline styling again so that it is clearer that it is a link on not just text, also better for our Lighthouse score

2024-03-26 21:43 UTC, johan-t commented on src/pages/App/App.tsx
> +const initialAppUIState: AppUIState = {
good restructure!

2024-03-27 09:31 UTC, brandesdavid commented
Alright i'm just gonna leave this for the moment

2024-03-27 09:36 UTC, johan-t commented
@brandesdavid but maybe if you want you could extract the stuff that made the map smoother and introduced the boundaries because that part was excellent and can be safely merged

2024-04-03 18:38 UTC, closed without merging